made getPastEvents public to enable listening to events when on http providers (#3949)
### Description

`getPastEvents` should be public to enable accessing events even on non ws connected provider connections. 

Right now it is like this
```
  protected getPastEvents(event: string, options: PastEventOptions): Promise<EventLog[]> {
    return this.contract.getPastEvents(event, options)
  }
```

which requires me to do this:
```
// @ts-ignore
        const events = await goldToken.contract.getPastEvents("Transfer", {
          fromBlock: 0,
          toBlock: 'latest'
        })
```

because the `events` collection is public and accessible via the wrapper but when i use `allEvents` or listen to a specific event like this:

`goldToken.events.allEvents({fromBlock: 0}, console.log)`

it will give me on http/s connections:

```
Error: The current provider doesn't support subscriptions: CeloProvider
    at Subscription.push../node_modules/web3-core-subscriptions/src/subscription.js.Subscription.subscribe (subscription.js:206)
    at Contract.push../node_modules/web3-eth-contract/src/index.js.Contract._on (index.js:646)
    at CeloTxs.tsx:23 null
```